services:
  db:
    image: postgres:16-alpine
    container_name: mini_system_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mini_system_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ..:/app
    command: ["bash", "-lc", "python -m generator.weather_generator"]
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppass}@db:5432/${POSTGRES_DB:-appdb}
      GEN_INTERVAL_SECONDS: "3"

    tty: true

  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mini_system_jupyter
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppass}@db:5432/${POSTGRES_DB:-appdb}
    volumes:
      - ..:/app
    ports:
      - "8888:8888"
    command: ["bash", "-lc", "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"]

volumes:
  pgdata:
